name: Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GH_PUBLISH_TOKEN:
        required: true

jobs:
  build:
    runs-on: superology-office
    outputs:
      new_release_published: ${{ steps.semantic_release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
    steps:
    - uses: actions/checkout@v1
    # - name: Setup Node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16.17.0'
    #     registry-url: https://npm.pkg.github.com/
    #     scope: '@company-name'
    # - name: Setup npm registry
    #   run: |
    #     echo //npm.pkg.github.com/:_authToken=$GH_TOKEN >> .npmrc
    #     echo @company-name:registry=https://npm.pkg.github.com/company-name >> .npmrc
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
    - name: Semantic Release
      id: semantic_release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
