name: Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      GH_PUBLISH_TOKEN:
        required: true

jobs:
  build:
    runs-on: superology-office
    outputs:
      new_release_published: ${{ steps.semantic_release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
    steps:
    - uses: actions/checkout@v1
    - name: Semantic Release
      id: semantic_release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
