name: CI

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Semantic Release
      id: semantic_release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
