name: Multiplatform Test

on:
  workflow_call:
jobs:
  check_prerequisites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check if required repo structure is present
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "packages/swift-package,packages/swift-package/Package.swift,packages/js-package,packages/js-package/package.json,shared,shared/build.gradle.kts,build-javascript.sh,.releaserc"
          allow_failure: true
  build:
    needs: check_prerequisites
    runs-on: superology-office
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          architecture: aarch64

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run :allTests
        run: ./gradlew :allTests

      - name: Run :detekt
        run: ./gradlew :detekt
  